[package]
name = "ngrok_simple"
version = "0.1.0"
authors = ["Johannes Dato <j@dato.rocks>"]
edition = "2018"

[[bin]]
name = "ngrok_simple"
path = "src/main.rs"

[dependencies]
url = "2.2.1"
ureq = { version = "1", features=["json"] }
thiserror = "1"
serde_json = "1"

[workspace]